name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-16.04
 
    steps:
    - uses: actions/checkout@v1
    - name: Build Console
      run: docker build . --file ./gaGO.io.MicrosoftOrleansDemo.ClientConsole/Dockerfile --tag my-image-name:$(date +%s)

    - uses: actions/checkout@v1
    - name: Build Silo
      run: docker build . --file ./gaGO.io.MicrosoftOrleansDemo.Silo/Dockerfile --tag my-image-name:$(date +%s)
